### ISSUE TITLE
build does not produce any artifact

### ISSUE THREAD

**Issue by Vincinator** [gardenlinux/builder_example#1]
How to reproduce:
```
git clone git@github.com:gardenlinux/builder_example.git
cd builder_example
./build
# .build/ folder is empty, no artifact were build 
```

I would expect the builder to create some artifact in `.build/` folder. No steps show up in the log.

**Comment by nkraetzschmar** [comment]
You need to specify a target or list of targets to be build with the syntax `./build ${targets}`.
For the example repo this would be `./build base`.

The builder does not yet support building a default target set if no targets are specified.

**Comment by MalteJ** [comment]
I think that's fine. We just need to enhance the docs a little bit.
